version: '2.4'
services:
  restfulDemodb:
    image: mysql:latest
    container_name: restfulDemo-db
    ports:
      - 3360:3306
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: restfuldemodb
  mockServer:
    image: mockserver/mockserver:latest
    user: root
    command: -serverPort 1090
    ports:
      - 1090:1090
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
