version: '3'
services:
  restfulDemodb:
    image: mysql:latest
    container_name: restfulDemo-db
    ports:
      - 3360:3306
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: restfuldemodb