version: '3'
services:
  restfulDemodb:
    image: mysql:latest
    container_name: restfulDemodb
    ports:
      - 6604:6604
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_ROOT_USER: restfuldemo_user
      MYSQL_DATABASE: restfulDemodb