spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3360/restfuldemodb
    username: root
    password: pass
    initialization-mode: always
    continue-on-error: true
  flyway:
    enabled: true
    validate-on-migrate: false

server:
  port: 8081

logging:
  file:
    path: logs
    name: RestfulDemoApplication.log

retry:
  attempts: 3
  backoff:
    delay: 500

user:
  authentication:
    url: http://localhost:1090
    do: true

customer:
  useDynamoDB: false

aws:
  s3:
    pricesS3Bucket:
      name: pluto-search-results-dev/prices
      reference: 2653b86a-15fc-4135-8cb2-331cb1775b38
      validate: false

cloud:
  aws:
    region:
      static: us-west-2
      auto: true
    stack:
      auto: false

